### ISSUE TITLE
Cannot use ref methods

### ISSUE THREAD

**Issue by paambaati** [Gamote/lottie-react#10]
**Describe the bug**
I'm trying to use the `goToAndPlay` method on an animation, and it errors out.

**To Reproduce**
1. Go to https://codesandbox.io/s/react-lottie-tryout-drhon?file=/src/App.tsx:1241-1252
2. Click on the 'Complete' button for the animation to skip to the 120th frame.
3. Watch that it throws an error on clicking the button.

**Expected behavior**
It shouldn't error and instead jump to the frame as intended.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS macOS Catalina 10.15.6
 - Browser Chrome
 - Version 87.0.4252.0 (Official Build) dev (x86_64)

**Additional context**
Initializing the `useRef` with default value `null` has the same effect.

**Comment by DaniAkash** [comment]
`lottieRef` prop only works on the `Lottie` component. It cannot be used on the `View` returned by `useLottie` hook. I have changed the code in the given codesandbox to use the `Lottie` component. It fixes the issue ✌🏽

**Comment by paambaati** [comment]
Thanks @DaniAkash!
