### ISSUE TITLE
onDataReady does not get called

### ISSUE THREAD

**Issue by ericvrp** [Gamote/lottie-react#14]
Are onDataReady and all others implemented? Because of #13 I am looking for a way to run the initial animation only once and was hoping to use `onDataReady={()=>lottieRef.current.playSegments(initialSegment)}` do do just that. 

My code does not get exectued though.

onDOMLoaded and onEnterFrame seem to be implemented

**Comment by Gamote** [comment]
Hi @ericvrp,

`data_ready` event is implemented in the same way as `DOMLoaded`, it must be a problem inside `lottie-web`.

**Comment by joeyfigaro** [comment]
@Gamote this is still an issue–did anything ever come of this?
