### ISSUE TITLE
playSegments does not stop when it comes to last frame

### ISSUE THREAD

**Issue by ivanjeremic** [Gamote/lottie-react#19]
My playSegments looks like this

````
playSegments([361, 400],);
````

but it plays without stopping.

What I want is just play on a button click to a specific frame and stop there. Did I something wrong?

**Comment by Gamote** [comment]
Hi @ivanjeremic,

Please create an example on [CodeSandbox](https://codesandbox.io) and I will have a look.

**Comment by ivanjeremic** [comment]
Adding the `initialSegment` solved the issue however I have issues now with sizing the svg is there any lottie-react discord or slack so I don't need to open new issues? thanks

**Comment by Gamote** [comment]
@ivanjeremic No, but I'm working on the v3 and with that I will open a Discord or Slack account.

**Comment by Gamote** [comment]
@ivanjeremic No, but I'm working on the v3 and with that I will open a Discord or Slack account. Thank you for suggesting and star this repo if you find it useful. 😄
