### ISSUE TITLE
Forward options to lottie-web

### ISSUE THREAD

**Issue by flo-sch** [Gamote/lottie-react#2]
Hello,

Nice wrapper, thanks for providing it :)

Would it be possible to forward all options from `useLottie()` to lottie-web (despite the ones that need to be controlled by the hook such as `container`?)
https://github.com/Gamote/lottie-react/blob/master/src/hooks/useLottie.js#L172

For instance, lottie-web allows different renderers such as `'svg' | 'canvas' | 'html'` with optional `rendererSettings`:
https://github.com/airbnb/lottie-web#other-loading-options

I think forwarding the full lottie-web config (easiest being as an object) would delegate the responsibility of rendering to lottie-web itself, which is what I would personally expect from such a wrapper.
It also has the benefit of making the integration more future-proof.

**Comment by Gamote** [comment]
Hi @flo-sch,

You've made an interesting point.

As you saw already [(useLottie.js#L172),](https://github.com/Gamote/lottie-react/blob/master/src/hooks/useLottie.js#L172) we were thinking to implement it but we wanted to make sure that we tested all the use cases before we allow it.

I must say that we couldn’t find any problem, so giving your view on future-proofing we will gonna release a new version soon which will include this.

**Comment by Gamote** [comment]
Implemented in [v1.1.2](https://github.com/Gamote/lottie-react/releases/tag/v1.1.2).

**Comment by flo-sch** [comment]
Wow, godspeed @Gamote! Thanks for the super quick fix :)
