### ISSUE TITLE
TypeError: Cannot read property 'current' of null

### ISSUE THREAD

**Issue by cailborg** [Gamote/lottie-react#3]
Not a huge deal, but it seems like `ref` seems to be a required prop. I was getting this error after following the docs unless I specified it, even though I have no need for interaction

**Comment by Gamote** [comment]
@cailborg Thank you for reporting, this commits should fix the problem: [f7e8722](https://github.com/Gamote/lottie-react/commit/f7e872253ad71fd9c88182fb5b3d64f515f5dc6a) and [4745727](https://github.com/Gamote/lottie-react/commit/47457271a30ad95bcca0ff2f283b2fe9bb528c50).

**Comment by Gamote** [comment]
@cailborg Thanks 👍. Fixed in [v1.2.2](https://github.com/Gamote/lottie-react/releases/tag/v1.2.2).
