### ISSUE TITLE
Lottie animations bottleneck the DOM

### ISSUE THREAD

**Issue by cZeaushe** [Gamote/lottie-react#32]
There's a weird issue with Lottie animations in React/Gatsby. I've tried many plugins like _react-lottie, lottie-react, lottie-web etc_. They all start bottlenecking the dom while navigating back and forth pages.

I've made an example with the issue: https://elegant-aryabhata-490c95.netlify.app/ If you navigate between the pages **Go to page 2** and **Go back to the homepage**, soon enough the DOM stops and the animation starts rendering extra stuff as well.

I am rendering the animations like so:
```
import * as React from "react"
import { Link } from "gatsby"

import Layout from "../components/layout"
import SEO from "../components/seo"

import Lottie from "lottie-react"
import contactAnimation from "../components/assets/contact.json"

const SecondPage = () => (
  <Layout>
    <SEO title="Page two" />
    <h1>Hi from the second page</h1>
    <p>Welcome to page 2</p>
    <Link to="/">Go back to the homepage</Link>
    <Lottie animationData={contactAnimation} style={{ width: "600px" }} />
  </Layout>
)

export default SecondPage
```
I have a plain HTML version as well https://upbeat-lewin-aabd01.netlify.app/ which has no issues. It looks like a memory leak or something but have no idea how to debug this.

**Comment by Gamote** [comment]
Hi @cZeaushe, can you please recreate the issue in CodeSandbox?

**Comment by cZeaushe** [comment]
I already sorted it out. It turns out to be a memory leak and happens if some of the Lottie animations us a **'repeater'**. All I had to do was `JSON.parse(JSON.stringify(data))` the animation json file and the problem was solved! 

```
import * as React from "react"
import { Link } from "gatsby"

import Layout from "../components/layout"
import SEO from "../components/seo"

import Lottie from "lottie-react"
import data from "../components/assets/contact.json"

const SecondPage = () => {
  const contactAnimation = JSON.parse(JSON.stringify(data))
  return (
    <Layout>
      <SEO title="Page two" />
      <h1>Hi from the second page</h1>
      <p>Welcome to page 2</p>
      <Link to="/">Go back to the homepage</Link>
      <Lottie animationData={contactAnimation} style={{ width: "600px" }} />
    </Layout>
  )
}

export default SecondPage
```

**Comment by Gamote** [comment]
@cZeaushe good to hear that you sort it out. 👍🏼
