### ISSUE TITLE
What is correct approach to having two animations on a single page, when using "useLottie" hook?

### ISSUE THREAD

**Issue by iceman121212** [Gamote/lottie-react#34]
**Describe the bug**
Unable to have two animations on a single page, using two calls to ```useLottie```

**To Reproduce**
https://codesandbox.io/s/lottie-react-hook-forked-rtwqp?file=/src/App.js

**Expected Behavior**
Would have expected there to be two instances of the animation on this page.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 91.0.4472.124 (Official Build) (64-bit)

**Comment by Gamote** [comment]
@iceman121212 Hmm, this sounds like a bug. I will try to fix it soon.

**Comment by fokysland** [comment]
It's not a bug, there's a mistake in your code: `const { View2 } = useLottie(options);`
useLottie returns an object with key View, but not View2. If you rewrite your code like this: `const { View : View2 }  = useLottie(options)`, it works
