### ISSUE TITLE
Recommended implementation for React and lottie-web with typescript ?

### ISSUE THREAD

**Issue by iangregsondev** [Gamote/lottie-react#36]
Hi,

I have been trying to find a typescript implementation and came across this, I found quite a few that's been abandoned. 

I was wondering if this is still under development and maintained?

Or is there an alternative I should be looking at.

Thanks in advance!

**Comment by Gamote** [comment]
Hi @iangregsondev, this package is still maintained. As was mentioned in other issues, we are trying to release the `v3` soon. We’ve been a bit busy with our 9 to 17 jobs but I can assure you that soon enough we are going to update the package.

Thank you for your interest in the package.

**Comment by iangregsondev** [comment]
Great stuff! Thanks.. Closing this now, going to have a play. Thanks again.
