### ISSUE TITLE
Passing interactivity adds another wrapping div that might break styling

### ISSUE THREAD

**Issue by NitayRabi** [Gamote/lottie-react#42]
**Describe the bug**

There's Inconsistent rendering behavior when passing `interactivity` prop - Another wrapping div is rendered, preventing passing relative sizes to through `style` or `className` prop (The wrapping div is rendered [here](https://github.com/Gamote/lottie-react/blob/main/src/hooks/useLottieInteractivity.tsx#L262), so passing 100% to width/height wouldn't be applied correctly) 

**To Reproduce**
1. Render `Lottie` with `style={{width: '100%', height: '100%'}}` within a div with set height and width
2. The animation will resize to fill containing div. 
3. Pass interactivity property - the animation will no longer fill containing div

**Expected behavior**
Passing interactivity shouldn't break DOM structure in such a way 

**Screenshots**
![image](https://user-images.githubusercontent.com/24541325/148736414-74d318f2-fc77-44ad-91c5-3b81caa4a0ea.png)

**Comment by Gamote** [comment]
@NitayRabi Thank you for reporting this. Yes you're right, it's on my todo list for the next version.

**Comment by Gamote** [comment]
Hey @NitayRabi, this bug was fixed in [v2.2.1](https://github.com/Gamote/lottie-react/releases/tag/v2.2.1).
