### ISSUE TITLE
type script error ( Property 'container' is missing )

### ISSUE THREAD

**Issue by EngHosam** [Gamote/lottie-react#49]
Property 'container' is missing in type '{ className: string; animationData: any; }' but required in type 'AnimationConfig<"svg">'.

**Comment by Gamote** [comment]
@EngHosam Please let me know which version you're using.

Also this problem was solved in [v2.2.1](https://github.com/Gamote/lottie-react/releases/tag/v2.2.1). Please check that out and let me know if you still encounter this issue. 🙂

**Comment by EngHosam** [comment]
yes, problem in current version
in `lottie-web` lib --> `index.d.ts` --> `AnimationConfig` --> `container: Element;` is required

**Comment by Gamote** [comment]
@EngHosam The only place where we're using the `AnimationConfig` (through `AnimationConfigWithData`) is in the `LottieOptions` type where we exclude the `container`. So I am not able to recreate the bug.

```ts
export type LottieOptions = Omit<AnimationConfigWithData, "container"> & {
  lottieRef?: LottieRef;
  onComplete?: AnimationEventHandler | null;
  onLoopComplete?: AnimationEventHandler | null;
  onEnterFrame?: AnimationEventHandler | null;
  onSegmentStart?: AnimationEventHandler | null;
  onConfigReady?: AnimationEventHandler | null;
  onDataReady?: AnimationEventHandler | null;
  onDataFailed?: AnimationEventHandler | null;
  onLoadedImages?: AnimationEventHandler | null;
  onDOMLoaded?: AnimationEventHandler | null;
  onDestroy?: AnimationEventHandler | null;
} & React.HTMLProps<HTMLDivElement>;
```

Can you provide an example of usage?

**Comment by EngHosam** [comment]
The error occur with typescript , when use Lottie component , I don't need to set container prop 
`<Lottie container (is required ) />`

**Comment by Gamote** [comment]
Using version `2.2.1` and `<Lottie animationData={....} />` I get no TypeScript errors.

**Comment by EngHosam** [comment]
Ok , I will retry , may be I need to invalidate cache and reinstall it ..

**Comment by Gamote** [comment]
Sometimes, the IDEs sends false positives after updating a library. I know WebStorm does. So yeah, please try to restart the IDE, clear the cache and try again. Please let me know, I will do my best to help you.

**Comment by EngHosam** [comment]
Thank you, Solved
