### ISSUE TITLE
typescript support?

### ISSUE THREAD

**Issue by helloalicesmith** [Gamote/lottie-react#5]
Where i can find "@types/lottie-react"?

**Comment by Gamote** [comment]
Hi @helloalicesmith,

All the types are defined in the project so you don't need another package.

Currently, on the version published on **npm**, the types are not exported properly but thanks to @vdh (#4), Typescript will be fully supported with the next release.

**Comment by Gamote** [comment]
@helloalicesmith This was solved in the **v2.0.0** release.
