### ISSUE TITLE
Animation loops not limited to specified count

### ISSUE THREAD

**Issue by alexanderbartl** [Gamote/lottie-react#51]
**Describe the bug**
After upgrading to version 2.2.1 of `lottie-react`, limiting the animation to a fixed number of loops does not work.

**To Reproduce**
1. Install v2.2.1 of `lottie-react` (e.g. in a fresh Create-React-App project)
2. Add the Lottie component:

        <Lottie animationData={data} loop={2} />
3. Open in browser, the animation will run indefinitely, as if `loop={true}` was set.

**Expected behavior**
The animation should play for the specified amount of loops.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 2.2.1

**Additional context**
The problem was not present with version 2.1.0. It feels like this might be related to #48.

**Comment by Gamote** [comment]
Hey @alexanderbartl, thank you for reporting. It will be fixed in the next release. 👍🏼

**Comment by Gamote** [comment]
This issue was fixed in [`v2.3.1`](https://github.com/Gamote/lottie-react/releases/tag/v2.3.1).
