### ISSUE TITLE
v3 Roadmap / prerelease?

### ISSUE THREAD

**Issue by MauriceArikoglu** [Gamote/lottie-react#52]
What's the current Roadmap for v3 and when can we expect a prerelease version for testing? Can we support?

**Comment by Gamote** [comment]
Hi @MauriceArikoglu, thank you for your interest in `lottie-react`. `v3` is almost done. These are the things that are left
- new interactivity functionality;
- determine the final configs available to the consumers;
- rewrite the documentation.

You can check the progress on the `v3` branch. Soon we will publish the `3.0.0-beta.0` on npm so everyone can test it. Once that is done, your feedback will be very welcome. Also it will be very useful if you can share if you are using `lottie-react` in production and what was your experience with it, pros and cons.

**Comment by Gamote** [comment]
Closing inactive issue. Please re-open if this require more information.
