### ISSUE TITLE
Wrong type for LottieComponentProps

### ISSUE THREAD

**Issue by irangarcia** [Gamote/lottie-react#65]
**Describe the bug**

Adding a path prop to the Lottie component is giving me a type error saying the path does not exist on the component props

**To Reproduce**
Add `path` prop to the <Lottie /> component

**Expected behavior**
Don't show me a type error

**Screenshots**

![Screenshot from 2022-07-05 11-50-02](https://user-images.githubusercontent.com/60601780/177356449-1b07734a-e64a-4b77-ba16-9e19a94c7757.png)

```Property 'path' does not exist on type 'IntrinsicAttributes & Omit<AnimationConfigWithData<"svg">, "container" | "animationData"> & { animationData: unknown; lottieRef?: LottieRef | undefined; ... 9 more ...; onDestroy?: AnimationEventHandler<...> | ... 1 more ... | undefined; } & Omit<...> & { ...; }'.```

**Comment by GhostyJade** [comment]
@irangarcia viewing [types declaration](https://github.com/Gamote/lottie-react/blob/main/src/types.ts) there's no "path" prop for the Lottie component (not even for the v3 branch). The type error you are seeing is generated by typescript and it's there by default. 
I don't think this is an issue with lottie-react.

I think that you want to set the animation data to display, right? In that case, use the ['animationData'](https://lottiereact.com/#animationdata) prop.

**Comment by irangarcia** [comment]
Yep, the problem is that does not exist in the types declarations. 

But the [lottie-web](https://github.com/airbnb/lottie-web#html) accepts two mutually exclusive params to load the animation:  `animationData` and `path`

I assume that in the v3 will be called [`src`](https://github.com/Gamote/lottie-react/blob/v3/src/%40types/types.ts#L63) that you can pass, what is now the `animationData` or `path`.

**Comment by avivnakar** [comment]
Another problem with `LottieComponentProps` is with React.lazy. there is mismatch between this type and the expected props for the component if loaded lazily.

 I think it is about ref and or children typing but not 100% sure.
If so, could be fixed by using some react types (such as FC, Props With Children etc...)

 I'll try to provide more information with code example later o

**Comment by irangarcia** [comment]
Workaroud for now:

Add/create `index.d.ts`

```ts
declare module 'lottie-react' {
    export interface LottieComponentProps extends LottieOptions {
        path: string;
    }
}
```

**Comment by acephillips** [comment]
@irangarcia Did you add the `index.d.ts` directly to `node_modules` for the package? Or was it added to a file in the component folder?

**Comment by irangarcia** [comment]
@acephillips root of the application
