### ISSUE TITLE
autoplay prop on component is not respected

### ISSUE THREAD

**Issue by MagnusHJensen** [Gamote/lottie-react#68]
**Describe the bug**
Autoplay on lottie component is not respected.

**To Reproduce**
1. <Lottie autoplay={false} />
2. See animation play on load.

**Expected behavior**
Component to respect autoplay prop.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser chrome
 - Version 103 (chrome)

**Comment by GhostyJade** [comment]
Can you provide a code example?

**Comment by MagnusHJensen** [comment]
Doesn't seem to be an issue anymore, not sure what was going at back then! Thanks anyways :D

**Comment by waaverecords** [comment]
I have the issue right now with version 2.4.1.

**Comment by waaverecords** [comment]
For anyone having this issue, there are two props at play here...
- autoPlay
- autoplay

autoplay is the correct one to use.
