### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Mithrandiirr** [Gamote/lottie-react#75]
I am trying to set lotties from a CDN, while doing so, I get an error `Cannot` read properties of undefined (reading 'length')` 
This is my code :
```
{missions.map((mission : any) => 
   (
<div className='bg-[#000000] flex-1'>
<Lottie animationData={mission?.manuscript?.asset.url} loop={true} />
</div>
   )}
```
The `mission?.manuscript?.asset.url}` is not undefined !

**Comment by GhostyJade** [comment]
Hey. If your asset.url is a string it won't work. Currently, v2 doesn't support loading data by url/string, it will be implemented in v3 as discussed in #15
