### ISSUE TITLE
Animation Glitches 

### ISSUE THREAD

**Issue by sedghi** [Gamote/lottie-react#76]
Hi, 
I need to show a loading indicator when my app is loading, however, the app load is a heavy task which makes the animation glitch as you see below. Is there any recommendation of how to fix this?

https://user-images.githubusercontent.com/7490180/195715458-566ed900-a432-4407-84cc-d7fd50d43347.mp4

I can confirm that the animation runs smoothly though on a lottie web player

Thanks

**Comment by GhostyJade** [comment]
@sedghi Have you tried to fetch your data using a service worker or something that doesn't block the main thread?
