### ISSUE TITLE
Incorrect type of "renderer" property of Lottie component

### ISSUE THREAD

**Issue by blurvene** [Gamote/lottie-react#77]
**Describe the bug**
Passing `renderer` property with value `"canvas" `or `"html"` to `Lottie` component triggers type error

**To Reproduce**
Pass `renderer="canvas"` or `renderer="html"` to `Lottie` component

**Expected behavior**
Typescript error is not displayed, `renderer` property accepts `'svg' | 'canvas' | 'html'` values

**Screenshots**
<img width="963" alt="Screenshot 2022-10-25 at 17 54 44" src="https://user-images.githubusercontent.com/34160673/197809624-cb8b8f7a-ebd4-4552-8fcf-cf1b9eba6fd8.png">

**Comment by Gamote** [comment]
@blurvene fixed in the [v2.4.0](https://github.com/Gamote/lottie-react/releases/tag/v2.4.0)
