### ISSUE TITLE
Error: <path> attribute d: Expected moveto path command ('M' or 'm')

### ISSUE THREAD

**Issue by cpellet** [Gamote/lottie-react#78]
**Describe the bug**
Lottie animations do not display properly, console gives the following error: `Error: <path> attribute d: Expected moveto path command ('M' or 'm')`

**To Reproduce**
Attempt to display the linked lottie animation as follows:
`<Lottie autoplay loop animationData={Angry}  rendererSettings={{preserveAspectRatio: 'xMidYMid slice'}}/>`

**Expected behavior**
The animation shows well in localhost development environment, but fails to load in production.

**Screenshots**
Only tiny parts of the animation are loaded:
![image](https://user-images.githubusercontent.com/18552249/203443737-e679659f-8ccb-4b23-b263-11c088104acf.png)
Whereas it is supposed to look like this (on localhost):
![image](https://user-images.githubusercontent.com/18552249/203443817-332ffc6c-83d0-4a00-b9d9-a4de57e16c0a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 107.0.5304.107 (Official Build) (64 bits) (cohort: Stable) 

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 16.1
 - Browser: Safari
 - Version : 16.1

**Additional context**

```
SVGShapeElement.renderInnerContent | @ | ea88be26-9bdc0959c76d7334.js:1
-- | -- | --
  | renderFrame | @ | ea88be26-9bdc0959c76d7334.js:1
  | SVGRendererBase.renderFrame | @ | ea88be26-9bdc0959c76d7334.js:1
  | AnimationItem.renderFrame | @ | ea88be26-9bdc0959c76d7334.js:1
  | AnimationItem.gotoFrame | @ | ea88be26-9bdc0959c76d7334.js:1
  | AnimationItem.setCurrentRawFrameValue | @ | ea88be26-9bdc0959c76d7334.js:1
  | AnimationItem.advanceTime | @ | ea88be26-9bdc0959c76d7334.js:1
```
[angry.zip](https://github.com/Gamote/lottie-react/files/10071885/angry.zip)

**Comment by mSauvestre** [comment]
Same issue here. For some reason, I also only get the issue when pushing to prod (Vercel) but not on localhost:
https://mythic-trap.vercel.app/vault/eranog

Animation is missing elements because of this for me too.

**Comment by cpellet** [comment]
> Same issue here. For some reason, I also only get the issue when pushing to prod (Vercel) but not on localhost: https://mythic-trap.vercel.app/vault/eranog
> 
> Animation is missing elements because of this for me too.

I actually found a fix, this seems to be Vercel's issue, see here: https://github.com/vercel/next.js/issues/42801. I will close this issue here.
