### ISSUE TITLE
Not working with next js

### ISSUE THREAD

**Issue by denvradiy** [Gamote/lottie-react#79]
**Describe the bug**
I use this package with nextjs. Lottie animation works locally but doesn't work on production build, it's not showing and throwing tons or the same errors : 

<img width="1728" alt="Screenshot 2022-11-25 at 00 29 29" src="https://user-images.githubusercontent.com/49561056/203870422-7b05b59a-486b-43a0-94bc-13d4b2ad42c0.png">

next version 13, lottie-react version 2.3.1

How can I fix this?

**Comment by pbozyk** [comment]
I have the same problem. It works when next is in development mode, but not after a production build. If you disable minimizing your webpack it will work. This is not a solution, just my observation :(

**Comment by Gamote** [comment]
@denvradiy @pbozyk Hello, please create a MRE (minimal reproducible example) and I will look into it.

**Comment by pbozyk** [comment]
Nothing specjal - standard configuration of NextJs with TaiwindCSS.  I think its a Next13 problem (TURBOPack).

    "next": "latest",
    "next-compose-plugins": "^2.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"

**Comment by Gamote** [comment]
It will greatly help and speed up the process if you guys create a MRE repo that I can use to recreate the issue. Thank you for your time.

**Comment by denvradiy** [comment]
I was creating a MRE repo and realised that lottie animation works with "next": "13.0.5", but my other project where I was using lottie-react has "next": "13.0.4" and it's not working there. @Gamote try  "next": "13.0.5". Looks like something was fixed

**Comment by denvradiy** [comment]
https://github.com/denvradiy/lottie-error 
@pbozyk here is MRE

**Comment by Gamote** [comment]
@denvradiy good to hear that you have found a fix. And thank you for taking the time to create the MRE.

@pbozyk can you try to see if `next@13.0.5` is fixing your issue as well?
