### ISSUE TITLE
is possible run with uri in react.js 

### ISSUE THREAD

**Issue by ahmettopal** [Gamote/lottie-react#80]
Hi, ı have lottie files in my cdn server and ı want to run with uri. is it possible ?

**Comment by ahmettopal** [comment]
> Hi, ı have lottie files in my cdn server and ı want to run with uri. is it possible ?

when ı try ım getting "Uncaught TypeError: Cannot read properties of undefined (reading 'length')" error

**Comment by Gamote** [comment]
Hey @ahmettopal, it is not possible at the moment to use remote animations. This will be available in the `v3`.

**Comment by ahmettopal** [comment]
> Hey @ahmettopal, it is not possible at the moment to use remote animations. This will be available in the `v3`.


I'm looking forward to v3
