### ISSUE TITLE
the lottie animation is rendering twice

### ISSUE THREAD

**Issue by shrutilenka** [Gamote/lottie-react#81]
**Describe the bug**
on adding lottie file to m react app,the animation is rendering twice

**Expected behavior**
it should be rendered only once 

**Screenshots**
![image](https://user-images.githubusercontent.com/96660357/216902971-b6b82f8d-12a5-489f-93a1-8a0aa0dbec5f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser - chrome,
 - lottie Version - 2.2.2

**Comment by Gamote** [comment]
Hi @shrutilenka , in the example mentioned above you are not using `lottie-react`.

**Comment by shrutilenka** [comment]
Thanks @Gamote
