### ISSUE TITLE
how to lottie interact scroll when element is fixed/sticky

### ISSUE THREAD

**Issue by lazarus2019** [Gamote/lottie-react#85]
example site: https://neverland.agency/

my code: `const Example = () => {
  const options = {
    animationData: LottieJson,
  };
  const lottieObj = useLottie(options);
  const Animation = useLottieInteractivity({
    lottieObj,
    mode: "scroll",
    actions: [
      {
        visibility: [0.2, 0.8],
        type: "seek",
        frames: [0, 493],
      },
    ],
  });

  return Animation;
};`

**Comment by jacobdejean** [comment]
You would need a structure like this:

```html
<div style={{ height: '200vh'  }}> // the height of this limits how long the lottie stays on screen
 <Example /> // your lottie
</div>
```

The lottie would then need to be animated over the duration of that parent div. This doesn't appear to be out of the box functionality with the lottie's interactions system. I've found `goToAndStop` useful for this. If you turn off autoplay, can just set frame position to `frameCount * percentOfParentProgress` on each scroll event. You can do the math manually or use a library like gsap.

I'm still unsure if this is the most ideal way of doing it, but it's been sufficient for me so far.

**Comment by lazarus2019** [comment]
> You would need a structure like this:
> 
> ```
> <div style={{ height: '200vh'  }}> // the height of this limits how long the lottie stays on screen
>  <Example /> // your lottie
> </div>
> ```
> 
> The lottie would then need to be animated over the duration of that parent div. This doesn't appear to be out of the box functionality with lottie's interactions system. I've found `goToAndStop` useful for this. If you turn off autoplay, can just set frame position to `frameCount * percentOfParentProgress` on each scroll event. You can do the math manually or use a library like gsap.
> 
> I'm still unsure if this is the most ideal way of doing it, but it's been sufficient for me so far.

thank you, I would try it and tell you back.

**Comment by lazarus2019** [comment]
It's work for me
![image](https://user-images.githubusercontent.com/62226062/224603022-464d8abb-de7a-4d2e-a451-3da9b9e9b346.png)
